config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    include PgSearch::Model
 pg_search_scope :search_full_text,
 against: {
UserName: 'A',
description: 'B',
 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    Pagy::DEFAULT[:items] = 10 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

 

  # GET /tweets or /tweets.json
  def index
    @pagy, @tweets = pagy(Tweet.all)

    if params[:query_text].present?
      @tweets = @tweets.search_full_text(params[:query_text])
      end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :UserName)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
include Pagy::Frontend
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500;700&display=swap" rel="stylesheet">
     <script src="https://kit.fontawesome.com/360cd4ba7a.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body class= "container row mx-auto">

  <div class= "col-xs-1 col-sm-1 col-m-1 col-lg-1 col-xl-1 col-xxl-1" id="menu"> 
      <%= render 'shared/menu' %>
  </div>

   <div class= "col-xs-7 col-sm-7 col-m-7 col-lg-7 col-xl-7 col-xxl-7" id="central"> 
        <%= yield %>
  </div>


  <div class= "col-xs-4 col-sm-4 col-m-4 col-lg-4 col-xl-4 col-xxl-4"> 
    <%= render 'shared/menud' %>
  </div>

   <script src="https://kit.fontawesome.com/360cd4ba7a.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_menu.html.erb
    <div class="bg-white text-dark row menu">
        <div class=" px-sm-2 px-0 ">
            <div class="d-flex flex-column align-items-center pt-2 min-vh-100 text-black" id="cambio">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto">
                    <span class="nav-link fs-5 d-none d-sm-inline pt-3"><i class="fa-brands fa-twitter fa-2xl" style="color: #00acee;"></i></span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="/tweets.html" class="nav-link align-middle px-0 ">
                            <i class="fa-solid fa-house-chimney-window fa-2xl icono" style="color: #000000;"></i> 
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link align-middle px-0 ">
                            <i class="fa-solid fa-hashtag fa-2xl ps-1 icono" style="color: #000000;"></i> 
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link align-middle px-0 ">
                            <i class="fa-regular fa-bell fa-2xl ps-1 icono" style="color: #000000;"></i> 
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link align-middle px-0 ">
                            <i class="fa-regular fa-envelope fa-2xl ps-1 icono" style="color: #000000;"></i> 
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link align-middle px-0 ">
                            <i class="fa-regular fa-bookmark fa-2xl ps-2 icono" style="color: #000000;"></i> 
                        </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link align-middle px-0">
                            <i class="fa-solid fa-list fa-2xl ps-1 icono" style="color: #000000;"></i>
                        </a>
                    </li>
                    <li>
                      <a href="#" class="nav-link align-middle px-0">
                        <img src="https://img.freepik.com/iconos-gratis/pikachu_318-196537.jpg" alt="hugenerd" width="40" height="40" class="rounded-circle">
                      </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link align-middle px-0">
                          <i class="fa-regular fa-comment-dots fa-2xl ps-1 icono" style="color: #000000;"></i> 
                        </a>
                    </li>
                    <li class="nav-link align-middle px-0" aria-current="page" >
                    <a href="/tweets/new.html"><i class="fa-solid fa-feather fa-2xl" style="color: #00acec;"> </i></a>
                    </li>
                </ul>
                </div>
            </div>
        </div>
    </div>

     <script src="https://kit.fontawesome.com/360cd4ba7a.js" crossorigin="anonymous"></script>

app/views/shared/_menud.html.erb

<div class= "py-4">
<%= form_with url: "/tweets", method: :get do |form|%>
<div>
 <%= form.text_field :query_text, placeholder: "🔍︎ Buscar en Twitter", value: params[:query_text], class:"busqueda container-fluid"%>
<%end%>
</div>
</div>

<div>
<h2 class="titulo">Santiago Trends</h2>
<hr>
<ul>
<li>1 - Trending</li>
<li class="hash">#DesafioLatam</li>
<li>44K Tweets</li>
<hr>
<li>2 - Trending</li>
<li class="hash">#ColoColo</li>
<li>30K Tweets</li>
<hr>
<li>3 - Trending</li>
<li class="hash">#Latierraesplana</li>
<li>12K Tweets</li>
<hr>
<li>4 - Trending</li>
<li class="hash"> #Lalunaesdequeso</li>
<li>9.2K Tweets</li>
<hr>
<li>5 - Trending</li>
<li class="hash">#elmañanaeshoy</li>
<li>8.3K Tweets</li>
</ul>
</div>

<div>
<h2 class="titulo pt-5"> ¿A quien Seguir?</h2>
<hr>
<div class="row ps-3">
    <p class="col-auto p-0">
        <a href="#" class="align-middle px-0">
        <img src="https://github.com/mdo.png" alt="hugenerd" width="50" height="50" class="rounded-circle">
        </a>
    </p>
    <div class="col-auto">
    <p class="m-0 pt-1" id="usuario3">
    Camilo Herrera
    </p>
    <p class="plomo">
    @camih
    </p>
    </div>
    <div class="col-auto ms-auto pt-2">
    <button type="button" class="btn btn-outline-primary">Seguir</button>
    </div>
    <hr>
</div>
<div class="row ps-3">
    <p class="col-auto p-0">
        <a href="#" class="align-middle px-0">
        <img src="https://i.discogs.com/2rmeHp16qfs8riIL2OKyl00_RliREf1nanlJmlZEvFU/rs:fit/g:sm/q:90/h:593/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTk2Mzcw/MDYtMTQ4Mzk5Nzgy/OS05ODQ4LmpwZWc.jpeg" alt="hugenerd" width="50" height="50" class="rounded-circle">
        </a>
    </p>
    <div class="col-auto">
    <p class="m-0 pt-1" id="usuario3">
    Mercedes Sosa
    </p>
    <p class="plomo">
    @Mersosa
    </p>
    </div>
    <div class="col-auto ms-auto pt-2">
    <button type="button" class="btn btn-outline-primary">Seguir</button> 
    </div>
    <hr>
</div>
<div class="row ps-3">
    <p class="col-auto p-0">
        <a href="#" class="align-middle px-0">
        <img src="https://www.canal9.cl/wp-content/uploads/2023/05/11.jpeg" alt="hugenerd" width="50" height="50" class="rounded-circle">
        </a>
    </p>
    <div class="col-auto">
    <p class="m-0 pt-1" id="usuario3">
    Chayanne
    </p>
    <p class="plomo">
    @ChayanneOficial
    </p>
    </div>
    <div class="col-auto ms-auto pt-2">
    <button type="button" class="btn btn-outline-primary">Seguir</button>
    </div>
    <hr>
</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div>
    <%= form.label "Nombre de usuario", style: "display: block" %>
    <%= form.text_field :UserName %>
  </div>

  <div>
    <%= form.label "Tweet", style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">


<div class="row">
  <p id="usuario" class="usuario col-auto">
    <strong></strong>
    <%= link_to tweet.UserName, tweet %>    
     </p>
    <p id="usuario2" class="col-auto">
    <%= "@#{tweet.UserName}"%>
  </p>
</div>

  
  <p id="tweet" class="pb-4">
    <strong></strong>
    <%= tweet.description %>
  </p>



</div>

app/views/tweets/edit.html.erb
<h1>Editar tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Mostrar este tweet", @tweet %> |
  <%= link_to "Volver a Twitter", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h2 class="pb-3 titulo">Inicio</h2>
<hr>

<div id="tweets">
  <% @tweets.each do |tweet| %>
    <%= render tweet %>
  <% end %>
  <div class="btn btn-primary">
  <%== pagy_nav(@pagy) if @pagy.pages >1  %>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Volver a Twitter", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div class="row">
  <%= link_to "Editar", edit_tweet_path(@tweet) %> 

  <%= button_to "Eliminar", @tweet, method: :delete %>
</div>